[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  JWT_SECRET = "CSIS3380Project"
  MONGODB_URI = "mongodb+srv://tongsik98:YFRPPjKG2KnhrHB3@cluster0.hozhwda.mongodb.net/myDatabase?retryWrites=true&w=majority"
